name: Builld LLDB

on: [push]

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: true

    - name: Build everything
      run: ./ci.sh


