name: Builld LLDB

on: [push]

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: true

    - name: Download dependencies
      run: ./download_dependencies.sh

    - name: Build lldb-server for Android arm64
      run: ANDROID_ABI=arm64-v8a ./build_lldb_server.sh

    - name: Build lldb-server for Android arm32
      run: echo "Skipping build for arm32..."

    - name: Upload lldb-server for Android arm64
        uses: actions/upload-artifact@v4
        with:
          name: lldb-server-arm64-${{ github.run_id }}
          path: build-arm64-v8a/out/bin/lldb-server
          if-no-files-found: 'error'
